{% set version = "1.0.1" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  sha256: d271096aede53830a3af3017f5cccd742e8f23445187f5ba1595e07ae1b980aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.16
    - scipy >=1.2
    - uncertainties >=3.0.1
    - asteval >=0.9.16

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
    Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize.leastsq, and with many additional classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
