{% set version = "1.0.3" %}
{% set name = "lmfit" %}
{% set sha256 = "d067c3ea501f035af5d3c079e6e6e35dc3cc1ac7d439429a425b0aeb5a7858a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - numpy >=1.18
    - scipy >=1.3
    - uncertainties >=3.1
    - asteval >=0.9.21

  run:
    - python >=3.6
    - pip
    - setuptools
    - numpy >=1.18
    - scipy >=1.3
    - uncertainties >=3.1
    - asteval >=0.9.21

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
    Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize.leastsq, and with many additional classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
