{% set version = "1.0.0" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  sha256: 4063249972290fcdee504f82332a74e61efb62c209007b00fd94db36dbeed870

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy >=0.19
    - six
    - uncertainties >=3.0
    - asteval >=0.9.12

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
