{% set version = "0.9.6" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  fn: lmfit-{{ version }}.tar.gz
  sha256: b77d514d547dc7179597603a06979e618a5d79b25ad38e1edcc6b43373a64985

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - emcee
    - numpy
    - python
    - scipy

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
