{% set version = "0.9.14" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  fn: lmfit-{{ version }}.tar.gz
  sha256: 4a175d4967fae218695178a750119bbabaec2a7b1dc66201b14ecb830c937f30

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
    - scipy >=0.19
    - six
    - uncertainties >=3.0
    - asteval >=0.9.12

  run:
    - python
    - numpy
    - scipy >=0.19
    - six
    - uncertainties >=3.0
    - asteval >=0.9.12

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
    - beckermr
