{% set version = "0.9.9" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  fn: lmfit-{{ version }}.tar.gz
  sha256: 55365311eb39f309e202ea56c57e06acb53c82d61ed46232f7dd474077801ddc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - six

  run:
    - python
    - numpy
    - scipy
    - six

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
