{% set version = "1.0.3" %}

package:
  name: lmfit
  version: {{ version }}

source:
  url: https://codeload.github.com/lmfit/lmfit-py/tar.gz//{{ version }}
  sha256: b3daa9f241ff4966c4e2a4710580c9e0237791f1c0e16d6334bb38979ec85b52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.18
    - scipy >=1.3
    - uncertainties >=3.0.1
    - asteval >=0.9.21

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
    Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize.leastsq, and with many additional classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
