{% set version = "1.3.1" %}
{% set name = "lmfit" %}
{% set sha256 = "2453b4f655a4a8c10292e0fb1a89c38d66dd65b330aa82e7690b2abbb7215925" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools-scm >=6.0
  run:
    - python >=3.8
    - pip
    - setuptools
    - setuptools-scm >=6.0
    - numpy >=1.19
    - scipy >=1.6
    - uncertainties >=3.1.4
    - asteval >=0.9.28
    - dill >=0.3.4

test:
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
    Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize.leastsq, and with many additional classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
