{% set version = "1.3.3" %}
{% set name = "lmfit" %}
{% set sha256 = "b1bb68df62a61f6dac9a3b8d920fd5323d8654a9af81fc0eaab11d052774b86c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lmfit/lmfit-py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm >=6.0
  run:
    - python >={{ python_min }}
    - pip
    - setuptools
    - numpy >=1.19
    - scipy >=1.6
    - uncertainties >=3.2.1
    - asteval >=1.0.0
    - dill >=0.3.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: >
    Non-Linear Least Squares Minimization, with flexible Parameter settings, based on scipy.optimize.leastsq, and with many additional classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - tacaswell
    - licode
    - newville
    - danielballan
    - tritemio
